# Generated by Django 2.2.6 on 2019-10-31 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_author', models.CharField(max_length=64)),
                ('post_drink', models.CharField(max_length=64, null=True)),
                ('post_text', models.CharField(max_length=200)),
                ('post_location', models.CharField(max_length=64, null=True)),
                ('post_score', models.IntegerField(default=0)),
                ('post_url', models.CharField(max_length=64, null=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=64)),
                ('comment_text', models.CharField(max_length=200)),
                ('comment_score', models.IntegerField(default=0)),
                ('comment_date', models.DateTimeField(verbose_name='date published')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
            ],
        ),
    ]
