# Generated by Django 2.2.6 on 2019-11-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20191113_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_url',
            field=models.CharField(default='posts/beer.png', max_length=64, null=True),
        ),
    ]
