# Generated by Django 2.2.6 on 2019-11-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20191117_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='drink_type',
            field=models.CharField(choices=[('WI', 'Wine'), ('BR', 'Beer'), ('CT', 'Cocktail'), ('SH', 'Shot')], default='CT', max_length=2),
        ),
    ]
