# Generated by Django 2.2.6 on 2019-11-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_drink_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='drink_type',
            field=models.CharField(choices=[('WI', 'wine'), ('BR', 'beer'), ('CT', 'cocktail'), ('SH', 'shot')], default='CT', max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_url',
            field=models.CharField(default='posts/cocktail.png', max_length=64, null=True),
        ),
    ]
