# Generated by Django 2.2.6 on 2019-11-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_likers'),
    ]

    operations = [
        migrations.AddField(
            model_name='likers',
            name='val',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
