# Generated by Django 2.2.6 on 2019-11-20 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_likers_val'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likers',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.Post'),
        ),
    ]
