package com.drinkup.api.models;

import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
 

@DynamoDBTable(tableName = "Posts")
public class Post implements Comparable<Post>{

    private String id;
    private String username;
    private String review;
    private String drink;
    private String location;
    private long createdDate=new Date().getTime();
    private int likes = 0;
    private int dislikes = 0;
    
    
    
    public Post() {}
    public Post(String username, String review, String drink,String location, long createdDate) {
    	this.username= username;
    	this.review = review;
    	this.drink = drink;
    	this.location = location;
    	this.createdDate = createdDate;
    }
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @DynamoDBAttribute
    public String getReview() {
        return review;
    }

    public void setReview(String review) {
        this.review = review;
    }
    @DynamoDBAttribute
    public String getDrink() {
        return drink;
    }

    public void setDrink(String drink) {
        this.drink = drink;
    }
    @DynamoDBAttribute
    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }
    @DynamoDBAttribute
    public long getCreatedDate() {
    	return createdDate; 
    }
    public void setCreatedDate(long createdDate) { 
    	this.createdDate = createdDate; 
    }
    @DynamoDBAttribute
    public int getLikes() {
        return likes;
    }

    public void setLikes(int likes) {
        this.likes = likes;
    }
    @DynamoDBAttribute
    public int getDislikes() {
        return dislikes;
    }

    public void setDislikes(int dislikes) {
        this.dislikes = dislikes;
    }
    public void incLikes() {
    	this.likes++;
    }
    public void decLikes() {
    	this.dislikes++;
    }
    
	@Override
	public int compareTo(Post post) {
		if(getCreatedDate()>post.getCreatedDate()) return 1;
		else if(getCreatedDate()==post.getCreatedDate())return 0;
		else return -1; 
	}
}