package com.drinkup.api.models;


import java.util.ArrayList;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;


@DynamoDBTable(tableName = "Users")
public class User {
	private String username;
	private String password;
	private List<String> reviews =  new ArrayList<String>();
	
	
	public User() {}
    public User(String username, String password, List<String> reviews) {
    	this.username= username;
    	this.password = password;
    	this.reviews = reviews;
    }
    
    @DynamoDBHashKey
    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }
    
    @DynamoDBAttribute
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
    
    @DynamoDBAttribute
    public List<String> getReviews() {
        return reviews;
    }

    public void setReviews(List<String> reviews) {
        this.reviews = reviews;
    }
    public void addReview(String review) {
    	this.reviews.add(review);
    }
    
    
    
}
